package com.tregouet.occam.alg.scoring.costs.definitions;

public enum DefinitionCostingStrategy {
	
	TRANSITION_COSTS, 
	TRANSITIONS_ENTROPY_REDUCTION, 
	PRODUCTIONS_ENTROPY_REDUCTION, 
	INSTANTIATIONS_ENTROPY_REDUCTION, 
	INSTANTIATIONS_ENTROPY_REDUCTION_OC

}
